-- 1. Create the contacts table
create table public.contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null
);

-- 2. Enable Row Level Security (RLS)
alter table public.contacts enable row level security;

-- 3. Create a policy to allow anyone (anon) to insert data
-- This is required for a public contact form
create policy "Enable insert for everyone" 
on public.contacts for insert 
to anon 
with check (true);

-- 4. Create a policy so only you (web dashboard) can read the data
-- This prevents random people from querying your contact messages
create policy "Enable read access for authenticated users only"
on public.contacts for select
to authenticated
using (true);
